### ISSUE TITLE
New gem release?

### ISSUE THREAD

**Issue by backus** [clarete/s3sync#37]
The s3sync install via rubygems just doesn't work

```sh
$ gem install s3sync
Fetching: cmdparse-3.0.1.gem (100%)
Successfully installed cmdparse-3.0.1
Fetching: s3sync-2.0.2.gem (100%)
Successfully installed s3sync-2.0.2
2 gems installed
$ s3sync help
/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/cmdparse-3.0.1/lib/cmdparse.rb:796:in `initialize': wrong number of arguments (1 for 0) (ArgumentError)
```

it looks like #35 fixed this though and installing from github seems to not produce the same errors

**Comment by darbyfrey** [comment]
+1 to this - lost some time on this bug today.

**Comment by wesley-ontoforce** [comment]
still having the issue: 
/opt/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/cmdparse-3.0.1/lib/cmdparse.rb:796:in `initialize': wrong number of arguments (1 for 0) (ArgumentError)
is there already a fix for this?

**Comment by sbelectronics** [comment]
Does anyone know how to solve this problem? I'm trying to install s3sync to a new server. I keep getting the following error:
    /usr/local/lib/ruby/gems/2.0.0/gems/cmdparse-3.0.1/lib/cmdparse.rb:796:in `initialize': wrong number of  arguments (1 for 0) (ArgumentError)
            from /usr/local/lib/ruby/gems/2.0.0/gems/s3sync-2.0.2/lib/s3sync/cli.rb:428:in `new'
            from /usr/local/lib/ruby/gems/2.0.0/gems/s3sync-2.0.2/lib/s3sync/cli.rb:428:in `run'
            from /usr/local/lib/ruby/gems/2.0.0/gems/s3sync-2.0.2/bin/s3sync:66:in `<top (required)>'
            from /usr/local/bin/s3sync:23:in `load'
            from /usr/local/bin/s3sync:23:in `<main>'

**Comment by clarete** [comment]
Sorry, I just pushed `v2.0.4` to rubygems.org. Since I received a PR that bumped it to `v2.0.3` and I didn't release it before applying another PR, I just created this new release instead.

I didn't push `v2.0.3` to `rubygems.org` because I'd have to update the `Gemfile.lock` and that would require another commit and I don't think it's worth the mess to release the retroactive version. Sorry about my lack of diligence here.

It's being a while that I started to use the `aws cli` command because of work, so I rarely have time for this guy. I'd be totally interested and getting some help. Let me know if any of you guys want to step in as contributors.
